services:
  server:
    image: ghcr.io/iamsarthakkr/university-management-api:${API_IMAGE_TAG:-latest}
    ports:
      - "127.0.0.1:8080:8080"

  frontend:
    image: ghcr.io/iamsarthakkr/university-management-frontend:${FRONTEND_IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
