spring:
  application:
    name: universityManagement
  jpa:
    show-sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:1800000}
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}
